<font style="font-size:28px;" align="left"><b>Vectors and Vector Computation</b></font>
<br>


A vector contains a list of numbers.

Using linear algebra, the state of a quantum system is described as a vector and is represented by a single column matrix.

In python a list or a numpy array can be used to represent a vector 

A list is a single object in python and a numpy can also be represented as a single object 

Similarly, a vector is a single mathematical object.

The dimension of a vector is the length of the number of values in taht vector

In [7]:
# let's denote a matrix using a list

a = [2, -3, 9, 4]

print ('Vector a is:', a)


Vector a is: [2, -3, 9, 4]


The Python NumPy module can be used to create a vector. We use numpy.array( ) method to create a one-dimensional array i.e. a vector. The numpy.array( ) method takes a list and then converts to a numpy array. The synatx is numpy.array(list)

In [6]:
# let's denote a vector using a numpy array

import numpy as np

b = np.array([2, -3, 9, 4])

print ('Vector b is:', b)

Vector b is: [ 2 -3  9  4]


### Vector multiplication (Scalar * Vector)

In [9]:
#using lists

a = [2, -3, 9, 4]

for i in range(len(a)):
    a[i] = 3 * a[i]
print("3a is",a)

    


3a is [6, -9, 27, 12]


In [16]:
# using numpy array

b = np.array([2, -3, 9, 4])

ans = 3*b

print (ans)

[ 6 -9 27 12]


### Vector Addition

Two vectors can be added if they are of the same dimension

In [13]:
# using lists

k = [2, -3, 9, 8, 2]

l = [-1, 4, -7, -2, 1]

new_vector=[]
for i in range(len(k)):
    new_vector.append(k[i]+l[i])

print("k+l is", new_vector)

# print the result vector similarly to a column vector
print() # print an empty line
print("the elements of k+l are")
for j in range(len(new_vector)):
    print(new_vector[j])


k+l is [1, 1, 2, 6, 3]

the elements of k+l are
1
1
2
6
3


In [18]:
# using numpy array

p = np.array([2, -3, 9, 8, 2])

q = np.array([-1, 4, -7, -2, 1])


new_vector2 = p + q

print("p+q is", new_vector2)

print("the elements of p+q are")
for i in range(len(new_vector2)):
    print(new_vector2[i])


p+q is [1 1 2 6 3]
the elements of p+q are
1
1
2
6
3


<font style="font-size:28px;" align="left"><b>Vectors: Dot (Scalar) Product</b></font>
<br>

Dot product is a specific way of defining multiplication between two vectors with the same size.

It is also called scalar product, because the result is a scalar value, e.g., a real number.

#### Using lists

In [22]:
# let's define both vectors
u = [-3,-2,0,-1,4]
v = [-1,-1,2,-3,5]

uv = 0; # summation is initially zero

for i in range(len(u)): # iteratively access every pair with the same indices
    print("pairwise multiplication of the entries with index",i,"is",u[i]*v[i])
    uv = uv + u[i]*v[i] # i-th entries are multiplied and then added to summation
    
print() # print an empty line    
print("The dot product of",u,'and',v,'is',uv)

pairwise multiplication of the entries with index 0 is 3
pairwise multiplication of the entries with index 1 is 2
pairwise multiplication of the entries with index 2 is 0
pairwise multiplication of the entries with index 3 is 3
pairwise multiplication of the entries with index 4 is 20

The dot product of [-3, -2, 0, -1, 4] and [-1, -1, 2, -3, 5] is 28


#### Using numpy array

In [23]:
u = [-3,-2,0,-1,4]
v = [-1,-1,2,-3,5]


vctr1 = np.array(u) 

vctr2= np.array(v) 


print("Vector created from a list u:") 
print(vctr1) 
print("Vector created from a list v:") 
print(vctr2) 

vctr_dot = vctr1.dot(vctr2)
print("Dot product of two vectors: ",vctr_dot)

Vector created from a list u:
[-3 -2  0 -1  4]
Vector created from a list v:
[-1 -1  2 -3  5]
Dot product of two vectors:  28


<h3> Orthogonal (perpendicular) vectors </h3>

Two vectors $Vi$  and $Vj$ are said to be orthogonal if they are perpendicular to each other. 
This means the dot or inner product of the two vector is zero.

This also means that the angle between them is $ 90 $ degrees. 

In [24]:
# for example these two vectors u and v are orthogonal
v = [-4,3]
u = [-3,-4]
result = 0;

for i in range(2):
    result = result + v[i]*u[i]

print("the dot product of u and v is",result)

the dot product of u and v is 0


<h3> Orthonormal vectors </h3>

A set of vectors $V$ is orthonormal if is it orthogonal and normalised.
This means every vector in $V$ has a unit magnitude of 1 and the set of vectors are mutually orthogonal


<h3> Tensor product of two vectors </h3>

We have two vectors: $ u = \begin{bmatrix}-2\\3\end{bmatrix}$ and $ v = \begin{bmatrix}1 \\ 2 \\ -3\end{bmatrix}$.

The tensor product of $u$ and $ v $ is denoted by $ u \otimes v $.

We may consider the tensor product as extending $ u $ by $ v $:

$$
    u \otimes v =  \begin{bmatrix}-2\\3\end{bmatrix} \otimes  \begin{bmatrix}1 \\ 2 \\ -3\end{bmatrix}=
   \begin{bmatrix} -2 \cdot \begin{bmatrix}1 \\ 2 \\ -3\end{bmatrix} \\ 3 \cdot  \begin{bmatrix}1 \\ 2 \\ -3\end{bmatrix} \end{bmatrix}=
   \begin{bmatrix}  -2 \\ -4 \\ 6 \\ 3 \\ 6 \\ -9 \end{bmatrix}.
$$

Here, $ -2 $ in $ u $ is replaced with the vector $ (-2  v) $, and $ 3 $ in $ u $ is replaced with the vector $ 3 v $.

Thus each entry of $ u $ is replaced by a 3-dimensional vector, and the dimension of the result vector is $ 6~(=2 \cdot 3) $.

Algorithmically, each element in $ u $ is replaced by the multiplication of this element with the vector $ v $.

Let's find $ v \otimes u $ in Python.

In [3]:
# vector v
v = [1,2,-3]
# vector u
u=[-2,3]

vu = []

for i in range(len(v)): # each element of v will be replaced
    for j in range(len(u)): # the vector u will come here after multiplying with the entry there
        vu.append( v[i] * u[j] )

print("v=",v)
print("u=",u)
print("vu=",vu)

v= [1, 2, -3]
u= [-2, 3]
vu= [-2, 3, -4, 6, 6, -9]
