# Data Encoding Using qiskit

### Basis Encoding

Basis encoding is a fundamental concept in quantum computing that involves preparing a quantum state in a specific basis. A basis in quantum computing refers to a set of orthogonal states that can be used to represent and manipulate qubits. The two most common bases used in quantum computing are the computational basis (also known as the Z basis) and the Hadamard basis (also known as the X basis).

1. Computational Basis (Z Basis) Encoding:
To encode a quantum state in the computational basis, you apply a Pauli-Z, Pauli-X, or Pauli-y gate or a phase gate to the qubit. 

2. Hadamard Basis (X Basis) Encoding:
To encode a quantum state in the Hadamard basis, you apply a Hadamard gate to the qubit. 

In [5]:
import math

In [11]:
# Import necessary libraries from Qiskit
from qiskit import QuantumCircuit, Aer, transpile, assemble
from qiskit.visualization import plot_bloch_multivector, plot_histogram, circuit_drawer

# Function to encode data into quantum states using Z basis encoding
def z_basis_encoding(data):
    n_qubits = len(data)
    qc = QuantumCircuit(n_qubits, n_qubits)

    for i, bit in enumerate(data):
        if bit == '1':
            qc.x(i)  # Apply X gate to qubits with classical bit value 1

    return qc

# Function to encode data into quantum states using Hadamard basis encoding
def hadamard_basis_encoding(data):
    n_qubits = len(data)
    qc = QuantumCircuit(n_qubits, n_qubits)

    for i, bit in enumerate(data):
        if bit == '1':
            qc.x(i)  # Apply X gate to qubits with classical bit value 1
        qc.h(i)  # Apply Hadamard gate to all qubits

    return qc

# Sample dataset
dataset = "1101"

# Z basis encoding example
z_basis_circuit = z_basis_encoding(dataset)
print("Z Basis Encoding Circuit:")
print(z_basis_circuit.draw())

# Hadamard basis encoding example
hadamard_basis_circuit = hadamard_basis_encoding(dataset)
print("\nHadamard Basis Encoding Circuit:")
print(hadamard_basis_circuit.draw())


Z Basis Encoding Circuit:
     ┌───┐
q_0: ┤ X ├
     ├───┤
q_1: ┤ X ├
     └───┘
q_2: ─────
     ┌───┐
q_3: ┤ X ├
     └───┘
c: 4/═════
          

Hadamard Basis Encoding Circuit:
     ┌───┐┌───┐
q_0: ┤ X ├┤ H ├
     ├───┤├───┤
q_1: ┤ X ├┤ H ├
     ├───┤└───┘
q_2: ┤ H ├─────
     ├───┤┌───┐
q_3: ┤ X ├┤ H ├
     └───┘└───┘
c: 4/══════════
               


----------------------------------------------------------------------------------------------------------------

### Amplitude Encoding

To encode the state
$$
    |x⟩ =  \frac1{\sqrt27.25} [1.5|00⟩+ 0.0|01⟩+0.0|10⟩- 5.0|11⟩]
$$
$$
    |x⟩ =  \frac1{\sqrt27.25} [1.5|00⟩- 5.0|11⟩] 
$$

In [18]:
desired_state = [
    1 / math.sqrt(27.25) * 1.5,
    0,
    0,
    1 / math.sqrt(27.25) * -5] ##Encode the quantum state to the appropraite quantum register
    

qc = QuantumCircuit(2) 
qc.initialize(desired_state, [0, 1])

qc.decompose().decompose().decompose().decompose().decompose().draw()

┌─────────┐              ┌───┐┌──────────┐┌──────────┐┌───┐»
q_0: ─|0>────┤ Ry(π/2) ├──────────────┤ X ├┤ Ry(-π/2) ├┤ Rz(-π/2) ├┤ X ├»
          ┌──┴─────────┴──┐┌─────────┐└─┬─┘└──────────┘└──────────┘└─┬─┘»
q_1: ─|0>─┤ R(2.5587,π/2) ├┤ U1(π/2) ├──■────────────────────────────■──»
          └───────────────┘└─────────┘                                  »
«     ┌─────────┐
«q_0: ┤ Rz(π/2) ├
«     └─────────┘
«q_1: ───────────
«

----------------------------------------------------------------------------------------------------------------

### Angle Encoding

To encode
$$
x =(0, \frac\pi{4}, \frac\pi{2})
$$
Note that
$$
angle  of  RY = 2 * value
$$

$$
number of qubit = number  of  features
$$

In [7]:
qc = QuantumCircuit(3)
qc.ry(0, 0)
qc.ry(2*math.pi/4, 1)
qc.ry(2*math.pi/2, 2)
qc.draw()

┌───────┐ 
q_0: ─┤ Ry(0) ├─
     ┌┴───────┴┐
q_1: ┤ Ry(π/2) ├
     └┬───────┬┘
q_2: ─┤ Ry(π) ├─
      └───────┘

Note that, if data set is given as decimal numbers: 
$$
angle = 2 * np.arcsin(value) 
$$
for example,  to encode 
$$
x = [0.7, -0.2, 0.9, -0.5]
$$
$$
angle for RY = [2 * np.arcsin(0.7), 2 * np.arcsin(-0.2), 2 * np.arcsin(0.9), 2 * np.arcsin(-0.5)]
$$

In [35]:
import numpy as np
from qiskit import QuantumCircuit, Aer, execute

def angle_encoding_circuit(data):
    n_qubits = len(data)
    qc = QuantumCircuit(n_qubits)

    # Apply the angle encoding gates
    for i, value in enumerate(data):
        angle = 2 * np.arcsin(value)  # Encode value as angle between -pi/2 and pi/2
        qc.rx(angle, i)  # Apply the rotation gate to the qubit

    return qc
print(encoding_circuit.draw())
# Encode the data using angle encoding
data_to_encode = [0.7, -0.2, 0.9, -0.5]
encoding_circuit = angle_encoding_circuit(data_to_encode)

# Simulate the quantum state after the encoding
backend = Aer.get_backend('statevector_simulator')
result = execute(encoding_circuit, backend).result()
statevector = result.get_statevector(encoding_circuit)

# Print the results

print("Data to Encode:", data_to_encode)
print("Encoded Quantum State:",statevector)



      ┌────────────┐ 
q_0: ─┤ Rx(1.5508) ├─
     ┌┴────────────┴┐
q_1: ┤ Rx(-0.40272) ├
     └┬────────────┬┘
q_2: ─┤ Rx(2.2395) ├─
      └┬──────────┬┘ 
q_3: ──┤ Rx(-π/3) ├──
       └──────────┘  
Data to Encode: [-0.6, 0.3, 0.1, -0.9]
Encoded Quantum State: Statevector([ 0.33098254+0.j        ,  0.        +0.2482369j ,
              0.        -0.10408919j,  0.07806689+0.j        ,
              0.        -0.033265j  ,  0.02494875+0.j        ,
             -0.01046136+0.j        ,  0.        -0.00784602j,
              0.        +0.68339342j, -0.51254506+0.j        ,
              0.21491729+0.j        ,  0.        +0.16118796j,
              0.06868362+0.j        ,  0.        +0.05151272j,
              0.        -0.0216j    ,  0.0162    +0.j        ],
            dims=(2, 2, 2, 2))


-------------------------------------------------------------------------------------------------------------

# Data Encoding using Pennylane

### Basis Embedding

In basis embedding, the data has to be in form of a binary string to get embedded. The idea behind basis embedding is using a computational basis. Approximating a scalar value to its binary form and then transforming it to a quantum state.

The algorithm involves — The first step is to approximate a number by a binary bit string and the second step is encoding it by a computational basis state. for instance: x=1001 is represented by the 4-qubit quantum state |1001⟩


In [53]:
from math import sqrt
import pennylane as qml


dev = qml.device('default.qubit', wires=3)

@qml.qnode(dev)
def circuit(feature_vector):
    qml.BasisEmbedding(features=feature_vector, wires=range(3))
    return qml.state()

X = [1,1,1]

In [54]:
print(qml.draw(circuit, expansion_strategy="device")(X))

0: ──X─┤  State
1: ──X─┤  State
2: ──X─┤  State


In [55]:
print(circuit(X))

[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j]


In [57]:
from math import sqrt
import pennylane as qml


dev = qml.device('default.qubit', wires=4)

@qml.qnode(dev)
def circuit(feature_vector):
    qml.BasisEmbedding(features=feature_vector, wires=range(4))
    return qml.state()

X = [0,1,0,1]

In [58]:
print(qml.draw(circuit, expansion_strategy="device")(X))

1: ──X─┤  State
3: ──X─┤  State


----------------------------------------------------------------------------------------------------------------

### Amplitude Embedding

In [43]:
import pennylane as qml

dev = qml.device('default.qubit', wires=2)

@qml.qnode(dev)
def circuit(f=None):
    qml.AmplitudeEmbedding(features=f, wires=range(2))
    return qml.expval(qml.PauliZ(0))

circuit(f=[1/2, 1/2, 1/2, 1/2])

tensor(0., requires_grad=True)

In [44]:
dev.state

tensor([0.5+0.j, 0.5+0.j, 0.5+0.j, 0.5+0.j], requires_grad=True)

#### Normalization: 
The template will raise an error if the feature input is not normalized. One can set normalize=True to automatically normalize it

In [46]:
import pennylane as qml

dev = qml.device('default.qubit', wires=2)

@qml.qnode(dev)
def circuit(f=None):
    qml.AmplitudeEmbedding(features=f, wires=range(2),normalize=True)
    return qml.expval(qml.PauliZ(1))

circuit(f=[10,20,30,40])

tensor(-0.33333333, requires_grad=True)

In [47]:
dev.state

tensor([0.18257419+0.j, 0.36514837+0.j, 0.54772256+0.j, 0.73029674+0.j], requires_grad=True)

#### Padding:
If the dimension of the feature vector is smaller than the number of amplitudes, one can automatically pad it with a constant for the missing dimensions using the pad_with option:

For example, if we have a feature vector f with 3 elements and want to use 2 qubits to represent the quantum state, you would need to pad the feature vector to have 4 elements, as 2^2 = 4. If you set pad_with=0, the feature vector would be automatically padded to [f[0], f[1], f[2], 0]

In [48]:
from math import sqrt
import pennylane as qml

dev = qml.device('default.qubit', wires=2)

@qml.qnode(dev)
def circuit(f=None):
    qml.AmplitudeEmbedding(features=f, wires=range(2), pad_with=0.)
    return qml.expval(qml.PauliZ(0))

circuit(f=[1/sqrt(2), 1/sqrt(2)])

tensor(1., requires_grad=True)

In [49]:
dev.state

tensor([0.70710678+0.j, 0.70710678+0.j, 0.        +0.j, 0.        +0.j], requires_grad=True)

----------------------------------------------------------------------------------------------------------

### Angle Embedding

The angle embedding is performed by applying rotations on the x-axis or y-axis using quantum gates along with the values that have to be encoded. If we wanna apply angle embedding on a dataset the number of rotations will be the same as the number of features in the dataset. the n-dimensional sample would take n-number of qubits to generate the set of quantum states.

In [51]:
from math import sqrt
import pennylane as qml
dev = qml.device('default.qubit', wires=3)

@qml.qnode(dev)
def circuit(feature_vector):
    qml.AngleEmbedding(features=feature_vector, wires=range(3), rotation='Z')
    qml.Hadamard(0)
    qml.Hadamard(1)
    qml.Hadamard(2)
    return qml.probs(wires=range(3))

X = [1/2,2,3/sqrt(2)]

In [52]:
print(qml.draw(circuit, expansion_strategy="device")(X))

0: ──RZ(0.50)──H─┤ ╭Probs
1: ──RZ(2.00)──H─┤ ├Probs
2: ──RZ(2.12)──H─┤ ╰Probs


In [59]:
from math import sqrt
import pennylane as qml
dev = qml.device('default.qubit', wires=6)

@qml.qnode(dev)
def circuit(feature_vector):
    qml.AngleEmbedding(features=feature_vector, wires=range(6), rotation='X')
    qml.Hadamard(0)
    qml.Hadamard(4)
    qml.Hadamard(5)
    qml.RX(0.5, wires=2)
    qml.RZ(0.7, wires=0)
    

    
    return qml.probs(wires=range(6))

X = [1/2,2,3/sqrt(2),1]


In [60]:
print(qml.draw(circuit, expansion_strategy="device")(X))


0: ──RX(0.50)──H─────────RZ(0.70)─┤ ╭Probs
1: ──RX(2.00)─────────────────────┤ ├Probs
2: ──RX(2.12)──RX(0.50)───────────┤ ├Probs
3: ──RX(1.00)─────────────────────┤ ├Probs
4: ──H────────────────────────────┤ ├Probs
5: ──H────────────────────────────┤ ╰Probs
